### ISSUE TITLE
Exception thrown: read access violation.

### ISSUE THREAD

**Issue by ghost** [keithalewis/xll12#11]
When I compile the current version of the source code and the code crashes with an read access violation.
test_base_derived() is called in test_handles()

![image](https://user-images.githubusercontent.com/33675621/46926164-99c90900-d06a-11e8-8eb1-3b05f0f0ae05.png)

I am on Windows 10, Visual Studio 2017 and Excel 2016 64 bit.

**Comment by keithalewis** [comment]
What project and configuration are you running? This is under active development. Have you cloned the most recent master branch?

**Comment by ghost** [comment]
I am running the test project with the newest code from git.

**Comment by keithalewis** [comment]
The 'newest code from git' is now 'Latest commit 146372a a minute ago'. Please include the SHA in bug reports.
I've moved the handle tests out of the test project to the xll.t project. These no longer depend on 64-bit Excel.

**Comment by ghost** [comment]
I did a git pull but the code still crashes in test_handles(void) when I runs the test_base_derived() method.

>git show
commit 0f09b65495254893f0103a021c3a5023cc8aa65a (HEAD -> master)

I am on debug, x64, Windows 10, Excel 2016

**Comment by keithalewis** [comment]
You need to learn how to use git. We all do. It is a horrible botch job, but we are stuck with it.
Do a fresh clone and try again. You should see
 $ git show
commit 146372a67f625fc3927ad7aeaeb700034e71fb2a (HEAD -> master, origin/master, origin/HEAD)

**Comment by ghost** [comment]
Works now!
Thank you!
