### ISSUE TITLE
Using xll:Excel to call internal functions

### ISSUE THREAD

**Issue by rentocika** [keithalewis/xll12#13]
In previos releases of xll I've something to determine path to *.xll file:
static int xll_open(void)
{
	static OPERX oGetName(Excel<XLOPERX>(xlGetName));
}
static Auto<OpenAfterX> xao_macro(xll_open);

But in current version I've got error that xll:Excel takes 2 arguments. The first is defined xlGetName? but what is second ?

**Comment by keithalewis** [comment]
I believe you are looking for [xll::Args::XlGetName()](https://github.com/keithalewis/xll12/blob/master/xll/args.h#L39).
