### ISSUE TITLE
License

### ISSUE THREAD

**Issue by markns** [keithalewis/xll12#2]
Hi,
Does this project have the same license as the older versions? eg. Microsoft Public License (Ms-PL). Would it be possible to specify it in the repository?
Thanks,
Mark

**Comment by keithalewis** [comment]
AFAICT very few people use this old technology. I'm busy with other
things now. Just tell me what you need and I'll try to make it happen 
for you.

**Comment by markns** [comment]
Old technology? Are you referring to Excel, C++ or the XLL lib itself?! Pretty sure Excel and C++ will never go out of fashion, therefore something that helps join the two together will always have a place right? :) Anyhow, I'm investigating the library for a small project, but without a license it's pretty much a non-starter. So - thanks for adding the license file.

I come from a managed code background, and have used Excel-DNA with success in the past. However, for this project I need to integrate a (secure) zeromq transport layer to a backend service, so have decided to swallow the C++ red pill. I've actually got a plugin working using XLLPlus, but having a closed-source dependency makes me a little uncomfortable. 

Couple more questions if you have a mo:

I notice there's no XLOPER subclassed in oper.h. Am I right in thinking that this means Excel <= 2003 is no longer supported? Not a massive deal for me, just curious.

Is there any other functionality that remains to be ported from the older versions?

**Comment by keithalewis** [comment]
I'm referring to the Excel SDK. I don't think Microsoft will commit any resources to this in the future.
I no longer support Excel 2003 and older.
No automatic help file generation is the main missing functionality.
Be sure to look into asynchronous functions if you are getting data over a network.
