### ISSUE TITLE
Example of optional argument

### ISSUE THREAD

**Issue by damian123** [keithalewis/xll12#5]
Do we have an example of an optional argument?

**Comment by keithalewis** [comment]
What do you mean by optional argument?

**Comment by damian123** [comment]
Sorry did not explain well. 
I mean in Excel you have a UDF with some arguments a, b, c.
I want argument c to be optional, so when I don't specify anything in XL it called into C.

**Comment by keithalewis** [comment]
Excel UDFs do not have default arguments. If an int, number, or string is missing in the call from Excel you will see 0, 0, or "", respectively. If the argument is an LPOPER and is not specified in the call from Excel you will get an OPER of type xltypeMissing. Up to you to figure out what default to supply.
(Thought you might have see the default arguments from the old version of xll. I will eventually fold those in.)

**Comment by keithalewis** [comment]
P.S. If the type is XLL_FP, then you cannot leave it missing.
