### ISSUE TITLE
Release mode build causing crash

### ISSUE THREAD

**Issue by damian123** [keithalewis/xll12#6]
When I build the test example in release mode and open it in Excel it crashes.

```
namespace xll {
	/// Manage the lifecycle of an Excel add-in.
	class AddIn {
	public:
		/// Register and Unregister an add-in when Excel calls xlAutoOpen and xlAutoClose.
		AddIn(const Args& args)
		{
--->			Auto<Open> ao([args]() { 
				return args.Register().isNum();
			});
```

![image](https://cloud.githubusercontent.com/assets/727816/20139081/9b0ddc8a-a684-11e6-8f2d-e22c153a462a.png)

![image](https://cloud.githubusercontent.com/assets/727816/20139116/c45fd25a-a684-11e6-9e6d-cf171c6be418.png)

**Comment by keithalewis** [comment]
Can reproduce. Will look this weekend.

**Comment by ittegrat** [comment]
I noticed that the crash is still there. Have you got any chance to spot the problem ?
It's a pity your nice library can't be used in release mode.

**Comment by keithalewis** [comment]
UTSL and send me a PR.

**Comment by keithalewis** [comment]
Fixed
