### ISSUE TITLE
handle delete crashes

### ISSUE THREAD

**Issue by damian123** [keithalewis/xll12#7]
When i run the test project and create a handle XLL.BASE(3) and then press Insert Function on the formula to bring up the argument helper the addin crashes.

![image](https://cloud.githubusercontent.com/assets/727816/20269106/24f6381a-aa82-11e6-9a7e-e6ac966f1947.png)

		static bool insert(T* p)
		{
			XLOPER12 caller, coerce;
			Excel12(xlfCaller, &caller, 0);
			Excel12(xlCoerce, &coerce, 1, &caller);
			if (coerce.xltype == xltypeNum && coerce.val.num != 0)
			{
				handle h(coerce.val.num);
				auto i = handles().find(h.ptr());
				if (i != handles().end())
		-->			delete *i;
			}
			return handles().insert(p).second;
		}

![image](https://cloud.githubusercontent.com/assets/727816/20269024/c61e08d6-aa81-11e6-8d1c-d37cf7409acb.png)

**Comment by keithalewis** [comment]
Fixed.
